apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
  namespace: frauddetectx
spec:
  template:
    spec:
      containers:
        - name: data-generator
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-processor
  namespace: frauddetectx
spec:
  template:
    spec:
      containers:
        - name: spark-processor
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-training
  namespace: frauddetectx
spec:
  template:
    spec:
      containers:
        - name: ml-training
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"