name: Build and Push Images

on:
  push:
    branches: [ main ]
    paths:
      - 'src/data-generator/**'
      - 'src/ml-training/**'
      - 'src/ml-metrics/**'
      - '.github/workflows/build-push.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push data-generator
        uses: docker/build-push-action@v4
        with:
          context: ./src/data-generator
          push: true
          tags: |
            ghcr.io/ajay6601/frauddetectx/data-generator:latest
            ghcr.io/ajay6601/frauddetectx/data-generator:${{ github.sha }}

      - name: Build and push ml-metrics
        uses: docker/build-push-action@v4
        with:
          context: ./src/ml-metrics
          push: true
          tags: |
            ghcr.io/ajay6601/frauddetectx/ml-metrics:latest
            ghcr.io/ajay6601/frauddetectx/ml-metrics:${{ github.sha }}

      - name: Build and push ml-training
        uses: docker/build-push-action@v4
        with:
          context: ./src/ml-training
          push: true
          tags: |
            ghcr.io/ajay6601/frauddetectx/ml-training:latest
            ghcr.io/ajay6601/frauddetectx/ml-training:${{ github.sha }}