apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - data-generator.yaml
  - ml-training.yaml
  - ml-metrics.yaml
  - monitoring.yaml