apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-metrics
  labels:
    app: ml-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-metrics
  template:
    metadata:
      labels:
        app: ml-metrics
    spec:
      containers:
        - name: ml-metrics
          image: ghcr.io/ajay6601/frauddetectx/ml-metrics:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: fraud_detection
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: METRICS_PORT
              value: "9188"
          ports:
            - containerPort: 9188
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-metrics
  labels:
    app: ml-metrics
spec:
  ports:
    - port: 9188
      targetPort: 9188
  selector:
    app: ml-metrics