apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-metrics
  namespace: frauddetectx
  labels:
    app.kubernetes.io/name: ml-metrics
    app.kubernetes.io/part-of: frauddetectx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ml-metrics
        app.kubernetes.io/part-of: frauddetectx
    spec:
      containers:
        - name: ml-metrics
          image: ghcr.io/Ajay6601/FraudDetectX/ml-metrics:latest
          ports:
            - containerPort: 9188
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: fraud_detection
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: METRICS_PORT
              value: "9188"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-metrics
  namespace: frauddetectx
  labels:
    app.kubernetes.io/name: ml-metrics
    app.kubernetes.io/part-of: frauddetectx
spec:
  ports:
    - port: 9188
      targetPort: 9188
      name: metrics
  selector:
    app.kubernetes.io/name: ml-metrics