apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-training
  labels:
    app: ml-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-training
  template:
    metadata:
      labels:
        app: ml-training
    spec:
      containers:
        - name: ml-training
          image: ghcr.io/ajay6601/frauddetectx/ml-training:latest
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: fraud_detection
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: REDIS_HOST
              value: redis
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379/0
          volumeMounts:
            - name: models-volume
              mountPath: /app/models
      volumes:
        - name: models-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ml-training
  labels:
    app: ml-training
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: ml-training