apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: frauddetectx
  labels:
    app.kubernetes.io/name: spark-master
    app.kubernetes.io/part-of: frauddetectx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-master
        app.kubernetes.io/part-of: frauddetectx
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:3.3
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: SPARK_MODE
              value: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: frauddetectx
  labels:
    app.kubernetes.io/name: spark-worker
    app.kubernetes.io/part-of: frauddetectx
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-worker
        app.kubernetes.io/part-of: frauddetectx
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark:3.3
          ports:
            - containerPort: 8081
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
            - name: SPARK_WORKER_MEMORY
              value: "2G"
            - name: SPARK_WORKER_CORES
              value: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-processor
  namespace: frauddetectx
  labels:
    app.kubernetes.io/name: spark-processor
    app.kubernetes.io/part-of: frauddetectx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-processor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-processor
        app.kubernetes.io/part-of: frauddetectx
    spec:
      containers:
        - name: spark-processor
          image: ghcr.io/Ajay6601/FraudDetectX/spark-processor:latest
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: bootstrap-servers
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: sasl-username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: sasl-password
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_SASL_MECHANISM
              value: PLAIN
            - name: KAFKA_TOPIC
              value: transactions
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: fraud_detection
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077